### ISSUE TITLE
Odysee iOS app Testing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#3]
@julianchandra commented on [Thu Jan 14 2021](https://github.com/lbryio/odysee-homepages/issues/45)

- [x] **1. Sign up Flow issue** - Critical
 If I sign up through mobile, I get the email verification, it opens the browser and I'm in Odysee on web.
But my mobile app doesn't do anything. 

- [ ] **Community guidelines + link to the help/support for Apple compliance** - Critical (no app allowed without this)
@tzarebczan we used to have a custom odysee contact/support page but it appears to be missing (redirects to lbry now).
If we can bring that back it might make things easier?
The user needs to be able to submit support requests through app (if needs to open your inbox that's ok) - mandatory.

**To test:**

- [x] Signing in and out (can't sign out once in)
- [x] Fire a video
- [x] Slime a video
- [x] Leave a comment (doesn't work)
- [x] Fire a comment (can't)
- [x] Slime a comment (can't)
- [x] Follow a channel
- [x] Unfollow a channel (doesn't work)
- [x] Tip a video
- [x] Tip a channel

**Missing features (for awareness - not necessarily mandatory right away, though profile/settings might be good to have):**

- [ ] Can't sync YT channel through sign up - so only end users can join through app, not creators
- [ ] Can't upload
- [ ] Can't access creator analytics
- [ ] Can't access profile/settings

---

@julianchandra commented on [Thu Jan 14 2021](https://github.com/lbryio/odysee-homepages/issues/45#issuecomment-759975872)

**Bugs**

- [x] I unfollowed a channel and it was still showing in my following even though in the channel profile it shows i'm not following them.

- [x] Gaming category won't load

- [x] Can't sign out once in.

- [x] Can't close the keyboard once open on a video page. 
You need to go out of it and back to close it.
![IMG-0510](https://user-images.githubusercontent.com/67612037/104556584-bff40e00-56a4-11eb-829c-1d1dc73b12cb.PNG)

- [ ] Seems impossible to scroll down to comments on certain videos because of too many related videos.
![IMG-0513](https://user-images.githubusercontent.com/67612037/104556630-cedac080-56a4-11eb-9f59-33ffd780735e.PNG)

- [ ]  Sometimes fire/slime etc are missing from below the video.
![IMG-0513](https://user-images.githubusercontent.com/67612037/104556644-d5693800-56a4-11eb-9143-9772d44b9ddd.PNG)

- [ ] Longer comments appear cropped, it's not clear if there are multiple comments or just one. I recommend we copy YT and put comments at the top below the fire/slime etc. Will attach the example of the issue and then the YT suggestion.
![comments weird](https://user-images.githubusercontent.com/67612037/104557085-8374e200-56a5-11eb-992d-006a2f90669f.png)

YOUTUBE example:
![IMG-0512](https://user-images.githubusercontent.com/67612037/104557111-8c65b380-56a5-11eb-8d2f-3d65d662add6.PNG)

**Design inconsistency - not a bug**
- [x] The avatar appears to be cropped differently from the normal circular shape.
![IMG-0514](https://user-images.githubusercontent.com/67612037/104556703-efa31600-56a4-11eb-9475-5d6b2c7a22b7.PNG)

**Comment by tzarebczan** [comment]
Can redirect the support menu option to: @OdyseeHelp:b About tab

**Comment by akinwale** [comment]
> Can't sign out once in.
This is intentional due to the way we're storing user state on the device, but the behaviour can be changed.

> Seems impossible to scroll down to comments on certain videos because of too many related videos.
This is actually the channel page. The comments are displayed differently (on a separate scrollable page) here. When viewing a video, a featured comment (truncated / cropped to 2 lines) is displayed at the bottom below the related content. You can tap on this area to view all the comments. I can move this to display above related content.

>  Sometimes fire/slime etc are missing from below the video.
Fire / Slime is displayed on the video page, not on the channel page.

Seems like there is some confusion differentiating between the video and channel views. Is there anything I can do to make the views more distinct?

> Leave a comment (doesn't work)
Fixed this. If you enter a comment less than 50 characters, it's supposed to show an error message. However, the keyboard blocks this error message. The keyboard is now being properly dismissed.

**Comment by julianchandra** [comment]
> > Can't sign out once in.
> 
> This is intentional due to the way we're storing user state on the device, but the behaviour can be changed.

Let's change something here, because it feels like the site it broken when I can't log out to change my account or something.


> This is actually the channel page. The comments are displayed differently (on a separate scrollable page) here. When viewing a video, a featured comment (truncated / cropped to 2 lines) is displayed at the bottom below the related content. You can tap on this area to view all the comments. I can move this to display above related content.

No, that was the video page itself, a video was above this. See the screenshot. 

> Fire / Slime is displayed on the video page, not on the channel page.

I meant video page. It doesn't show sometimes.

**Comment by julianchandra** [comment]
- [ ] I am forced to follow channels, if I click 'done' I am prompted with error 'please follow channel' - can you you make it so that the done button will allow the new user to not have to follow anyone?

- [ ] Issue with channel thumbnails on screen where you have to choose channels to follow
![IMG-0533](https://user-images.githubusercontent.com/67612037/105001557-d5967880-5a94-11eb-859e-0bd305d1b3a8.PNG)

- [ ] Could we remove these tags from below the channel which appear really out of place.
![IMG-0537](https://user-images.githubusercontent.com/67612037/105001667-ffe83600-5a94-11eb-96a7-cb5cb8ccf152.PNG)

- [ ] Still can't fire/slime other's comments.
![IMG-0539](https://user-images.githubusercontent.com/67612037/105001710-10001580-5a95-11eb-8754-6e73e94289dc.PNG)

- [ ] Keyboard issue - after entering channel name, cannot scroll down to save/edit profile because keyboard is in the way.
![IMG-0540](https://user-images.githubusercontent.com/67612037/105001766-260dd600-5a95-11eb-8e6b-7aa3e6377d52.PNG)

- [ ] Avatars missing next to comments
![unnamed](https://user-images.githubusercontent.com/67612037/105002090-9d436a00-5a95-11eb-89a1-64affecded9a.jpg)

**Comment by akinwale** [comment]
> I am forced to follow channels, if I click 'done' I am prompted with error 'please follow channel' - can you you make it so that the done button will allow the new user to not have to follow anyone?

This is the whole point with the Following view. Without following anyone, we wouldn't have any content to display on the screen. One feature I would like to add here is the ability to search for creators, but you can always navigate other parts of the app without doing anything here.

> Still can't fire/slime other's comments.

Do you have a channel created? I can add a message that states that you can only fire / slime if you have a channel.

> Avatars missing next to comments

Sometimes, avatars may fail to load due to timeouts. I need to implement a way to handle loading errors and fallback to the spaceman image.
