### ISSUE TITLE
Cannot sign in with Password manager 

### ISSUE THREAD

**Issue by iMonZ** [lbryio/odysee-ios#68]
Currently, it’s not possible to sign in with the existing password manager (or sign up on the website) which is terrible for the app!

**Comment by tzarebczan** [comment]
Are you referring to odysee.com? This is a known issue and filed in another repo.

**Comment by iMonZ** [comment]
> Are you referring to odysee.com? This is a known issue and filed in another repo.

The issue occurs on the website and inside the app!

**Comment by tzarebczan** [comment]
Are you able to use a password manager in other apps ? How does it show up?

**Comment by iMonZ** [comment]
> Are you able to use a password manager in other apps ? How does it show up?

Its actually pretty easy:
When you try to create an account it automatically recommends you your saved email addresses and generates a secure password.
Both the email address/username and password are going to be saved in your password manager of your choice.

If you try to log in it looks up the database and recommends you automatically to use the already saved login credentials that are encrypted on an external chip.

And that's basically it!

Here is a small Twitter example:

**Comment by tzarebczan** [comment]
Thank you for the additional information!

**Comment by anohren** [comment]
I wanted to confirm this but when I checked I didn't even have my Odysee credentials in any of my iOS password managers. This probably indicates that iOS didn't identify the password field upon signing up, which is basically the same problem. It's a guess, but seems plausible. 

I can't remember if I signed up in the app or in the website, but I've had to use the magic link ever since, as far as I can recall. 

I think it'd be a big benefit to support password managers as soon as possible, considering it's part of first impressions.

**Comment by iMonZ** [comment]
You can press on more passwords.
But it still must recommend you that and with creating an account it should save that in the keychain.

**Comment by anohren** [comment]
Sorry, I'm not sure what you're saying.

**Comment by iMonZ** [comment]
Oh so my PR is merged.
Im waiting for the AppStore update if it works I will close this issue

**Comment by iMonZ** [comment]
Isn’t the iOS app missing from this list?: https://lbry.tech/contribute

**Comment by tzarebczan** [comment]
Yep, we gotta add that...fairly new still.

**Comment by iMonZ** [comment]
@akinwale Hey, could you please bump up the version? Thanks
